---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - persistentvolumes/finalizers
  verbs:
  - update
- resources:
  - persistentvolumes/status
  verbs:
  - get
  - patch
  - update
